@startuml
skinparam classAttributeIconSize 0

abstract class ApplicationAdapter {
    + ApplicationAdapter()
    + create()
    + resize()
    + render()
    + pause()
    + resume()
    + dispose()
}

class Game extends ApplicationAdapter {
    + create()
    + render()
    + setControllerState(newState: Controller)
}

package controllers {
    abstract class Controller {
        # state : GameState
        + Controller(game : Game, view : View, state : GameState)
    }

    class MainMenuController extends Controller {

    }

    class GamePlayController extends Controller {

    }
}

package views {
    abstract class View {
        + {abstract}render()
    }

    class MainMenuView extends View {
        +render()
    }

    class GamePlayView extends View {
        +render()
    }
}

package models {
    abstract class Model {

    }
}

package core {
    enum GameState {
        MAIN_MENU
        GAME_PLAY
    }
}

Game "1\ngame" --> "1\ncurrentController" Controller
Controller -right-> "1" View : view
Controller o-down-> "*" Model : models

@enduml