@startuml
skinparam classAttributeIconSize 0

abstract class Game {
    + ApplicationAdapter()
    + create()
    + resize(width: int, height: int)
    + render()
    + pause()
    + resume()
    + dispose()
    + setScreen(screen: Screen)
    + getScreen() : Screen
}


class RevNRun extends Game {
    - batch: SpriteBatch
    - shapeRenderer: ShapeRenderer
    + create()
    + render()
    + resize()
}

package controllers {
    package screens {
        class ScreenAdapter {
            + ScreenAdapter()
            + create()
            + resize(width: int, height: int)
            + render(delta: float)
            + pause()
            + resume()
            + dispose()
        }

        abstract class Controller extends ScreenAdapter {
            + Controller(game: Game, batch: SpriteBatch)
            + {abstract}execute()
            + resize(width: int, height: int)
            # update()
        }

        class MainMenuController extends Controller {
            + execute()
        }

        class GamePlayController extends Controller {
            + execute()
        }
    }

    package input {
        interface InputHelper {
            + isKeyPressed(int keycode): boolean
        }

        class LibGDXInputHelper implements InputHelper {

        }

        class InputHandler {

        }
    }
}

package views {
    abstract class View {
        # viewport: Viewport
        # camera: Camera
        # batch: SpriteBatch

        + {abstract} render()
        + resize(width: int, height: int)
    }

    class MainMenuView extends View{
        +render()
    }

    class GamePlayView extends View {
        +render()
    }
}

package models {

}

package core {
    enum GameState {
        MAIN_MENU
        GAME_PLAY
    }
}

RevNRun "1\ngame" --> "1\ncurrentController" Controller
Controller --> View : view
Controller --> InputHandler : input
InputHandler --> InputHelper : inputHelper

input -[hidden]right- screens

@enduml