name: Code Style Check

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  style-check:
    name: Style Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate style checker script
        run: |
          chmod +x ./.github/scripts/java-style-checker.sh

      - name: Run style checker
        run: |
          ./.github/scripts/java-style-checker.sh
        continue-on-error: false